from enum import Enum, unique

@unique
class MeboCommands(Enum):
    READERS = "READERS"
    FACTORY = "FACTORY"
    BAT = "BAT"
    
    WHEEL_LEFT_FORWARD = "WHEEL_LEFT_FORWARD"
    WHEEL_LEFT_BACKWARD = "WHEEL_LEFT_BACKWARD"
    WHEEL_RIGHT_FORWARD = "WHEEL_RIGHT_FORWARD"
    WHEEL_RIGHT_BACKWARD = "WHEEL_RIGHT_BACKWARD"
    WHEEL_BOTH_STOP = "WHEEL_BOTH_STOP"

    ARM_UP = "ARM_UP"
    ARM_DOWN = "ARM_DOWN"
    ARM_POSITION = "ARM_POSITION"
    ARM_STOP = "ARM_STOP"
    ARM_QUERY = "ARM_QUERY"

    WRIST_UD_UP = "WRIST_UD_UP"
    WRIST_UD_DOWN = "WRIST_UD_DOWN"
    WRIST_UD_POSITION = "WRIST_UD_POSITION"
    WRIST_UD_STOP = "WRIST_UD_STOP"
    WRIST_UD_QUERY = "WRIST_UD_QUERY"

    WRIST_ROTATE_LEFT = "WRIST_ROTATE_LEFT"
    WRIST_ROTATE_RIGHT = "WRIST_ROTATE_RIGHT"
    WRIST_ROTATE_POSITION = "WRIST_ROTATE_POSITION"
    WRIST_ROTATE_STOP = "WRIST_ROTATE_STOP"
    WRIST_ROTATE_QUERY = "WRIST_ROTATE_QUERY"

    CLAW_POSITION = "CLAW_POSITION"
    CLAW_STOP = "CLAW_STOP"
    CLAW_QUERY = "CLAW_QUERY"

    SET_TURNING_SPEED_1 = "SET_TURNING_SPEED_1"
    SET_TURNING_SPEED_2 = "SET_TURNING_SPEED_2"
    SET_TURNING_SPEED_3 = "SET_TURNING_SPEED_3"
    
    CAL_ARM = "CAL_ARM"
    CAL_WRIST_UD = "CAL_WRIST_UD"
    CAL_WRIST_ROTATE = "CAL_WRIST_ROTATE"
    CAL_CLAW = "CAL_CLAW"
    CAL_ALL = "CAL_ALL"

    VERSION_QUERY = "VERSION_QUERY"
    REBOOT_CMD = "REBOOT_CMD"
    JOINT_SPEED = "JOINT_SPEED"

    SET_REG = "SET_REG"
    QUERY_REG = "QUERY_REG"
    SAVE_REG = "SAVE_REG"

    WHEEL_LEFT_SPEED = "WHEEL_LEFT_SPEED"
    WHEEL_RIGHT_SPEED = "WHEEL_RIGHT_SPEED"

    QUERY_EVENT = "QUERY_EVENT"
    NONE = "NONE"
