#!/bin/bash
# suggested use for this:
# (1) Put in the ids for your robot, YOURROBOTID and YOURCAMERAID
# (2) use sudo to create a crontab entry: @reboot /bin/bash /home/pi/start_robot
cd /home/pi/runmyrobot
nohup scripts/repeat_start python controller.py ${input_robot} --type mebo2 &> /dev/null &
nohup scripts/repeat_start python send_video.py ${input_camera} 0 --kbps 2000 &> /dev/null &